#!/usr/bin/env bash
#<------------------------------CLI Application for managing TRASH------------------------------------>
# author : @tribhuwan-kumar
# email : freakybytes@duck.com
#<------------------------------------------------------------------------------------------>

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'
TRASH_FILES_DIR="$HOME/.local/share/Trash/files"
TRASH_INFO_DIR="$HOME/.local/share/Trash/info"
TOTAL_SIZE=$(du -sh "$TRASH_FILES_DIR" | cut -f1)

# consider file name is a file & a directory too
formatting() {
    local FILENAME="$1"
    local FILESIZE="$2"
    printf "%-8s %s\n" "$FILESIZE" "$FILENAME"
}

ask_confirmation() {
    read -p "Are you sure you want to empty the trash? This action can't be undone. [y/N] " RESPONSE
    case "$RESPONSE" in
        [yY][eE][sS]|[yY]) 
            return 0
            ;;
        *)
            echo "Operation cancelled!!"
            exit 1
            ;;
    esac
}

create_trashinfo() {
    local FILE_PATH="$1"
    local TRASHINFO_PATH="$TRASH_INFO_DIR/$(basename "$FILE_PATH").trashinfo"
    local CURRENT_TIME=$(date +%Y-%m-%dT%H:%M:%S)
    local ORIGINAL_PATH=$(python3 -c "import urllib.parse; print(urllib.parse.quote('$FILE_PATH'))")

    echo "[Trash Info]" > "$TRASHINFO_PATH"
    echo "Path=$ORIGINAL_PATH" >> "$TRASHINFO_PATH"
    echo "DeletionDate=$CURRENT_TIME" >> "$TRASHINFO_PATH"
}

# Manage relative paths
get_absolute_path() {
    local REL_PATH="$1"
    if [[ "$REL_PATH" == /* ]]; then
        echo "$REL_PATH"
    else
        echo "$(pwd)/$REL_PATH"
    fi
}

# Help
if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "trashbhuwan" ]]; then
    echo -e "Usage: trashbhuwan [OPTION] [FILE]...\nTrashing & Restoring files\n\nExample: trashbhuwan --put file directory\nPuts file and directory in trash\n\nAvaiable flags:\n    -p,  --put          Put files & directories in trash\n    -r,  --restore      Restore files from the trash\n    -ls, --list         List trashed files\n    -dl, --delete       Delete trashed files & directories\n    -em, --empty        Empty the trash"
    exit 0
fi

# DU trash
if [[ "$1" == "--list" ]] || [[ "$1" == "-ls" ]]; then
    printf "${YELLOW}%-8s${NC} ${YELLOW}%s${NC}\\n" "SIZE" "FILES & DIRECTORIES"
     if [ -z "$(ls -A "$TRASH_FILES_DIR")" ]; then
        echo -e "\nTrash is empty!!\n"
    else
        for ITEM in "$TRASH_FILES_DIR"/*; do
            SIZE=$(du -sh "$ITEM" | cut -f1)
            ITEM=$(basename "$ITEM")
            formatting "$ITEM" "$SIZE" 
        done
    fi
    printf "${YELLOW}%-8s${NC} ${YELLOW}%s${NC}\\n" "$TOTAL_SIZE" "TOTAL SIZE"  
    exit 0
fi

# Delete trashed files
if [[ "$1" == "--delete" ]] || [[ "$1" == "-dl" ]]; then
    for FILE_NAME in "${@:2}"; do
        if [ -e "$TRASH_FILES_DIR/$FILE_NAME" ]; then
            ESCAPED_FILE_NAME=$(printf '%q' "$FILE_NAME")
            TRASH_INFO_FILE=$(find "$TRASH_INFO_DIR" -name "*$ESCAPED_FILE_NAME.trashinfo*")
            if [ -n "$TRASH_INFO_FILE" ]; then
                rm -rf "${TRASH_FILES_DIR:?}/${FILE_NAME:?}"
                rm -rf "${TRASH_INFO_FILE:?}"
                wait $!
                printf "${GREEN}%s${NC} %s\\n" "$FILE_NAME" "is deleted from trash!"
            else
                printf "%s ${RED}%s${NC}\\n" "Couldn't find .trashinfo file for" "$FILE_NAME"
            fi
        else
            printf "${RED}%s${NC} %s\\n" "$FILE_NAME" "is not found in the trash!"
        fi
    done
    exit 0
fi

# Empty trash
if [[ "$1" == "--empty" ]] || [[ "$1" == "-em" ]]; then
    ask_confirmation
    printf "${GREEN}%s${NC}\\n" "Emptying the trash..."
    rm -rf "${TRASH_FILES_DIR:?}"/*
    rm -rf "${TRASH_INFO_DIR:?}"/*
    wait $!
    printf "${GREEN}%s${NC}\\n" "Trash has been emptied!!"
    exit 0
fi

# Put files in trash
if [[ "$1" == "--put" ]] || [[ "$1" == "-p" ]]; then
    for FILE_NAME in "${@:2}"; do
        # kioclient5 move "$FILE_NAME" trash:/ # for kde users
        FILE_PATH=$(get_absolute_path "$FILE_NAME") 
        if [ -e "$FILE_PATH" ]; then 
            mv "$FILE_NAME" "$TRASH_FILES_DIR"
            create_trashinfo "$FILE_PATH"
            printf "${GREEN}%s${NC} %s\\n" "$FILE_NAME" "is trashed!!"
        else
            printf "${RED}%s${NC} %s\\n" "$FILE_NAME" "does not exist!!"
        fi
    done
    exit 0
fi

# Restoration of files
if [[ "$1" == "--restore" ]] || [[ "$1" == "-r" ]]; then
    for FILE_NAME in "${@:2}"; do
        if [ -e "$TRASH_FILES_DIR/$FILE_NAME" ]; then
            ESCAPED_FILE_NAME=$(printf '%q' "$FILE_NAME")
            TRASH_INFO_FILE=$(find "$TRASH_INFO_DIR" -name "*$ESCAPED_FILE_NAME.trashinfo*")
            if [ -n "$TRASH_INFO_FILE" ]; then 
                ORIGINAL_PATH=$(grep "Path=" "$TRASH_INFO_FILE" | sed 's/Path=//' | xargs -I {} sh -c 'python3 -c "import urllib.parse; print(urllib.parse.unquote(\"{}\"))"')
                DIRECTORY=$(dirname "$ORIGINAL_PATH")
                if [ -n "$ORIGINAL_PATH" ]; then
                    if [ ! -d "$DIRECTORY" ]; then
                        printf "%s ${YELLOW}%s${NC} %s \n%s \n%s \n%s \n${YELLOW}%s${NC}\\n" "The directory" "$DIRECTORY" "doesn't exist anymore," "So it isn't possible to restore this item to its original path." "You can either recreate that directory & use the restore command again," "Or move that item anywhere else to restore it." "ITEM PATH: $TRASH_FILES_DIR/$FILE_NAME"
                        exit 0
                    fi
                    mv "$TRASH_FILES_DIR/$FILE_NAME" "$ORIGINAL_PATH"
                    printf "%s ${GREEN}%s${NC} %s ${GREEN}%s${NC}\\n" "Restored" "$FILE_NAME" "to" "$DIRECTORY"  
                else
                    printf "%s ${RED}%s${NC}\\n" "Couldn't find original path for" "$FILE_NAME"  
                fi
            else
                printf "%s ${RED}%s${NC}\\n" "Couldn't find original path for" "$FILE_NAME"   
            fi
        else
            printf "%s ${RED}%s${NC} %s\\n" "Couldn't find" "$FILE_NAME" "in trash"
        fi
    done
fi

# Check for the arguments
if [ $# -eq 0 ]; then
    printf "${RED}%s${NC}\\n" "󰋼 No arguments were provided, See the github page https://github.com/tribhuwan-kumar/trashbhuwan for usage."
    exit 1
fi

if [[ "$1" != "--list" && "$1" != "-ls" && "$1" != "--empty" && "$1" != "-em" && "$1" != "--put" && "$1" != "-p" && "$1" != "--restore" && "$1" != "-r" && "$1" != "--delete" && "$1" != "-dl" ]]; then
    printf "${RED}%s${NC}\\n" "Invalid option: $1"
    echo "Usage: [--list|-ls] [--put|-p] [--restore|-r] [--delete|-dl] [--empty|-em] [FILE]...[DIRECTORY]"
    exit 1
fi
